/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObraIdRouteImport } from './routes/obra.$id'
import { Route as CompletedIdRouteImport } from './routes/completed.$id'
import { Route as ChecklistIdRouteImport } from './routes/checklist.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraIdRoute = ObraIdRouteImport.update({
  id: '/obra/$id',
  path: '/obra/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedIdRoute = CompletedIdRouteImport.update({
  id: '/completed/$id',
  path: '/completed/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistIdRoute = ChecklistIdRouteImport.update({
  id: '/checklist/$id',
  path: '/checklist/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/obras': typeof ObrasRoute
  '/upload': typeof UploadRoute
  '/checklist/$id': typeof ChecklistIdRoute
  '/completed/$id': typeof CompletedIdRoute
  '/obra/$id': typeof ObraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/obras': typeof ObrasRoute
  '/upload': typeof UploadRoute
  '/checklist/$id': typeof ChecklistIdRoute
  '/completed/$id': typeof CompletedIdRoute
  '/obra/$id': typeof ObraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/obras': typeof ObrasRoute
  '/upload': typeof UploadRoute
  '/checklist/$id': typeof ChecklistIdRoute
  '/completed/$id': typeof CompletedIdRoute
  '/obra/$id': typeof ObraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/obras'
    | '/upload'
    | '/checklist/$id'
    | '/completed/$id'
    | '/obra/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/obras'
    | '/upload'
    | '/checklist/$id'
    | '/completed/$id'
    | '/obra/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/obras'
    | '/upload'
    | '/checklist/$id'
    | '/completed/$id'
    | '/obra/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ObrasRoute: typeof ObrasRoute
  UploadRoute: typeof UploadRoute
  ChecklistIdRoute: typeof ChecklistIdRoute
  CompletedIdRoute: typeof CompletedIdRoute
  ObraIdRoute: typeof ObraIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra/$id': {
      id: '/obra/$id'
      path: '/obra/$id'
      fullPath: '/obra/$id'
      preLoaderRoute: typeof ObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed/$id': {
      id: '/completed/$id'
      path: '/completed/$id'
      fullPath: '/completed/$id'
      preLoaderRoute: typeof CompletedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist/$id': {
      id: '/checklist/$id'
      path: '/checklist/$id'
      fullPath: '/checklist/$id'
      preLoaderRoute: typeof ChecklistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ObrasRoute: ObrasRoute,
  UploadRoute: UploadRoute,
  ChecklistIdRoute: ChecklistIdRoute,
  CompletedIdRoute: CompletedIdRoute,
  ObraIdRoute: ObraIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
